# Generated by Django 3.1.7 on 2021-03-18 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_auto_20210318_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
    ]
