# Generated by Django 3.1.7 on 2021-04-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_auto_20210318_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='Id')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('url', models.TextField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Exploit',
                'verbose_name_plural': 'Exploits',
                'db_table': 'exploit',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='activo',
            name='impacto',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=5, verbose_name='Impacto'),
        ),
        migrations.AlterField(
            model_name='equipored',
            name='tipoEquipo',
            field=models.CharField(choices=[('Gateway', 'Gateway'), ('Interfaz', 'Interfaz'), ('Router', 'Router'), ('Switch', 'Switch')], max_length=8, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='tipoHardware',
            field=models.CharField(choices=[('Periférico', 'Periférico'), ('Servidor', 'Servidor'), ('Sensor', 'Sensor'), ('Actuador', 'Actuador'), ('Ordenador', 'Ordenador'), ('No determinado', 'No determinado'), ('Equipo de red', 'Equipo de red'), ('Smartphone', 'Smartphone')], max_length=14, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='estado',
            field=models.CharField(choices=[('Abiero', 'Abiero'), ('Cerrado', 'Cerrado'), ('Filtrado', 'Filtrado')], max_length=8, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='software',
            name='tipoSoftware',
            field=models.CharField(choices=[('Sistema operativo', 'Sistema operativo'), ('Firmware', 'Firmware'), ('Antivirus', 'Antivirus'), ('Aplicación Móvil', 'Aplicación Móvil'), ('Código', 'Código')], max_length=17, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='Id')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('url', models.TextField(verbose_name='URL')),
                ('activo', models.ManyToManyField(to='activos.Activo')),
                ('exploit', models.ManyToManyField(to='activos.Exploit')),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Vulnerabilidades',
                'db_table': 'vulnerabilidad',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='exploit',
            name='activo',
            field=models.ManyToManyField(to='activos.Activo'),
        ),
    ]
