# Generated by Django 3.1.7 on 2021-04-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_auto_20210412_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='protocolo',
        ),
        migrations.AddField(
            model_name='plugin',
            name='protocolo',
            field=models.ManyToManyField(blank=True, null=True, to='activos.Protocolo'),
        ),
    ]
