# Generated by Django 3.1.7 on 2021-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_auto_20210412_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo',
            name='puerto',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='puerto',
            field=models.ManyToManyField(blank=True, null=True, to='activos.Puerto'),
        ),
    ]
