# Generated by Django 3.1.7 on 2021-04-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_auto_20210412_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puerto',
            options={'ordering': ['id'], 'verbose_name': 'Puerto', 'verbose_name_plural': 'Puertos'},
        ),
    ]
