# Generated by Django 3.1.7 on 2021-05-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_remove_vulnerabilidad_exploit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilidad',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='vulnerabilidades/%d/%m/%Y/', verbose_name='Archivo'),
        ),
        migrations.DeleteModel(
            name='Exploit',
        ),
    ]
