# Generated by Django 3.1.7 on 2021-05-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_remove_vulnerabilidad_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='vulnerabilidades/%Y/%m/%d/', verbose_name='Archivo'),
        ),
    ]
