# Generated by Django 3.1.7 on 2021-05-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_auto_20210518_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='activo',
            field=models.ManyToManyField(to='activos.Activo'),
        ),
    ]
